parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
  - master

pool: default


jobs:
  - job: 
    steps:
      - 

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'