parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: false
  values:
  - false
  - true
trigger:
  - master

pool: default


#name: "ubuntu-latest"


jobs:
  - job: 
    steps:
      - script: echo "hello"
   
