parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
  - master

pool: default


jobs:
    - job: display
      steps:
      - script: echo Hello, world!

