parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
  - master

pool:
  vmImage: "windows-latest"

jobs:
    - job: display
      steps:
      - script: echo Hello, world!

